/*
  The instrument catalog — ONE source for what every market IS.

  This used to live twice: 137 names in lib/symbols.ts for the web's
  autocomplete, and a richer 182-entry catalog bundled in the iOS app.
  They drifted, and the drift was visible — searching "NOVO" found
  nothing because Novo Nordisk existed in one and not the other.

  Generated from the app's catalog, which was the fuller of the two.
  Keep this file the source: the search route matches against it, and any
  client that wants profiles should read it rather than carry its own.
*/

export type Instrument = {
  symbol: string;
  name: string;
  sector: string;
  /** What the thing actually does, in a sentence a beginner can use. */
  what: string;
  /** What tends to move the price. */
  moves: string;
};

export const INSTRUMENTS: Instrument[] = [
  { symbol: "AAPL", name: "Apple Inc.", sector: "Consumer technology",
    what: "Makes the iPhone, Mac, iPad, Watch and AirPods, and runs the App Store and iCloud services on top of them.",
    moves: "iPhone sales cycles and the growth of its services business." },
  { symbol: "MSFT", name: "Microsoft Corporation", sector: "Software & cloud",
    what: "Sells Windows and Office, and runs Azure \u2014 the world's second-largest cloud platform. Also owns LinkedIn, GitHub and Xbox.",
    moves: "Azure's growth rate and enterprise software spending." },
  { symbol: "NVDA", name: "NVIDIA Corporation", sector: "Semiconductors",
    what: "Designs the GPUs that train and run almost all modern AI, plus chips for gaming and data centres.",
    moves: "AI data-centre demand \u2014 its results move the whole chip sector." },
  { symbol: "AMZN", name: "Amazon.com, Inc.", sector: "E-commerce & cloud",
    what: "Runs the world's largest online store and AWS, the biggest cloud computing platform. Also owns Prime Video and Whole Foods.",
    moves: "AWS growth and retail margins, which are thin by design." },
  { symbol: "GOOG", name: "Alphabet Inc.", sector: "Internet & advertising",
    what: "Google's parent: search, YouTube, Android, Chrome and Google Cloud. Most of the money still comes from advertising.",
    moves: "Search ad spending and how AI reshapes search." },
  { symbol: "META", name: "Meta Platforms, Inc.", sector: "Social media",
    what: "Owns Facebook, Instagram, WhatsApp and Threads, and spends heavily on AI and virtual reality (Reality Labs).",
    moves: "Ad revenue per user and how much it burns on the metaverse." },
  { symbol: "TSLA", name: "Tesla, Inc.", sector: "Electric vehicles",
    what: "Builds electric cars, batteries and solar products, and is betting on self-driving software and robots.",
    moves: "Delivery numbers, price cuts, and belief in its self-driving promises." },
  { symbol: "AMD", name: "Advanced Micro Devices, Inc.", sector: "Semiconductors",
    what: "Makes CPUs and GPUs that compete directly with Intel and NVIDIA, in PCs, servers and game consoles.",
    moves: "Server-chip share gains and its distant second place in AI silicon." },
  { symbol: "NFLX", name: "Netflix, Inc.", sector: "Streaming media",
    what: "The largest subscription streaming service, now also selling a cheaper ad-supported tier and live events.",
    moves: "Subscriber additions and how well the ad tier sells." },
  { symbol: "AVGO", name: "Broadcom Inc.", sector: "Semiconductors & software",
    what: "Makes networking, broadband and custom AI chips, and owns VMware's enterprise software business.",
    moves: "Custom AI chip orders from the big cloud providers." },
  { symbol: "INTC", name: "Intel Corporation", sector: "Semiconductors",
    what: "The classic PC and server chipmaker, now trying to become a contract manufacturer for other companies' designs.",
    moves: "Whether its expensive factory build-out wins outside customers." },
  { symbol: "MU", name: "Micron Technology, Inc.", sector: "Semiconductors",
    what: "Makes memory chips \u2014 DRAM and flash storage \u2014 including the high-bandwidth memory that AI accelerators need.",
    moves: "Memory prices, which swing hard in boom-and-bust cycles." },
  { symbol: "CRM", name: "Salesforce, Inc.", sector: "Enterprise software",
    what: "Sells the cloud software companies use to track customers, sales and support.",
    moves: "Seat growth and corporate software budgets." },
  { symbol: "ORCL", name: "Oracle Corporation", sector: "Enterprise software & cloud",
    what: "Database software for large institutions, now aggressively renting out AI cloud capacity.",
    moves: "Cloud backlog \u2014 the contracts it has signed but not yet delivered." },
  { symbol: "ADBE", name: "Adobe Inc.", sector: "Creative software",
    what: "Photoshop, Illustrator, Premiere and Acrobat, all sold as subscriptions.",
    moves: "Whether AI image tools expand its market or erode it." },
  { symbol: "PLTR", name: "Palantir Technologies Inc.", sector: "Data & AI software",
    what: "Builds data-analysis platforms for governments, defence agencies and large companies.",
    moves: "Government contract awards and its commercial expansion." },
  { symbol: "SMCI", name: "Super Micro Computer, Inc.", sector: "Server hardware",
    what: "Assembles the physical servers and racks that data centres fill with AI chips.",
    moves: "AI build-out spending \u2014 and a history of accounting controversy." },
  { symbol: "COIN", name: "Coinbase Global, Inc.", sector: "Crypto exchange",
    what: "The largest US crypto exchange, earning fees when people trade digital assets.",
    moves: "Crypto prices and trading volume \u2014 it is a leveraged bet on the sector." },
  { symbol: "JPM", name: "JPMorgan Chase & Co.", sector: "Banking",
    what: "The largest US bank: consumer accounts, corporate lending, investment banking and trading.",
    moves: "Interest rates and credit losses across the economy." },
  { symbol: "BAC", name: "Bank of America Corporation", sector: "Banking",
    what: "A giant consumer and commercial bank, with a huge portfolio of deposits and loans.",
    moves: "Rate moves \u2014 it is unusually sensitive to them." },
  { symbol: "GS", name: "The Goldman Sachs Group, Inc.", sector: "Investment banking",
    what: "Advises on mergers, underwrites share sales, and trades for institutions.",
    moves: "Deal activity and market volatility." },
  { symbol: "V", name: "Visa Inc.", sector: "Payments network",
    what: "Runs the rails that carry card payments between banks. It takes a small cut of the spending; it does not lend.",
    moves: "Consumer spending volume and cross-border travel." },
  { symbol: "MA", name: "Mastercard Incorporated", sector: "Payments network",
    what: "Visa's direct competitor \u2014 the second global card network, also a toll on spending rather than a lender.",
    moves: "Payment volumes and international travel." },
  { symbol: "BRK.B", name: "Berkshire Hathaway Inc. (Class B)", sector: "Conglomerate",
    what: "Warren Buffett's holding company: insurance (GEICO), railways (BNSF), energy, plus a huge stock portfolio led by Apple.",
    moves: "The performance of its subsidiaries and its enormous cash pile." },
  { symbol: "UNH", name: "UnitedHealth Group Incorporated", sector: "Health insurance",
    what: "The largest US health insurer, and through Optum, a huge provider of care and pharmacy services.",
    moves: "Medical cost ratios \u2014 how much of each premium goes to care." },
  { symbol: "LLY", name: "Eli Lilly and Company", sector: "Pharmaceuticals",
    what: "Drugmaker behind the weight-loss and diabetes treatments Mounjaro and Zepbound.",
    moves: "Obesity-drug demand and manufacturing capacity." },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Pharmaceuticals",
    what: "Prescription medicines and medical devices, after spinning off its consumer brands.",
    moves: "Drug pipelines and litigation over talc and opioids." },
  { symbol: "XOM", name: "Exxon Mobil Corporation", sector: "Oil & gas",
    what: "One of the largest integrated oil companies: it drills, refines and sells fuel worldwide.",
    moves: "The price of crude oil, more than anything it does itself." },
  { symbol: "CVX", name: "Chevron Corporation", sector: "Oil & gas",
    what: "Integrated oil major with major operations in the Permian Basin and Kazakhstan.",
    moves: "Crude prices and production growth." },
  { symbol: "WMT", name: "Walmart Inc.", sector: "Retail",
    what: "The largest retailer on earth by revenue, and increasingly an online and advertising business too.",
    moves: "Grocery traffic and how thrifty shoppers are feeling." },
  { symbol: "COST", name: "Costco Wholesale Corporation", sector: "Retail",
    what: "Membership warehouse clubs \u2014 most of the actual profit comes from membership fees, not the goods.",
    moves: "Membership renewal rates and fee increases." },
  { symbol: "HD", name: "The Home Depot, Inc.", sector: "Retail",
    what: "The biggest home-improvement chain, serving both homeowners and contractors.",
    moves: "Housing turnover and mortgage rates." },
  { symbol: "MCD", name: "McDonald's Corporation", sector: "Restaurants",
    what: "The largest fast-food chain \u2014 and, in practice, a giant franchiser and property owner.",
    moves: "Same-store sales and value-menu pricing." },
  { symbol: "KO", name: "The Coca-Cola Company", sector: "Beverages",
    what: "Sells concentrate and brands to bottlers worldwide: Coke, Sprite, Fanta, Dasani.",
    moves: "Pricing power and currency swings abroad." },
  { symbol: "PEP", name: "PepsiCo, Inc.", sector: "Food & beverages",
    what: "Pepsi drinks plus Frito-Lay snacks and Quaker foods \u2014 the snack half is the bigger profit engine.",
    moves: "Snack volumes and input costs." },
  { symbol: "DIS", name: "The Walt Disney Company", sector: "Media & entertainment",
    what: "Film studios, ESPN, ABC, theme parks and cruise lines, plus Disney+ streaming.",
    moves: "Park attendance and streaming profitability." },
  { symbol: "BA", name: "The Boeing Company", sector: "Aerospace & defence",
    what: "Builds commercial jets and defence systems \u2014 one half of the world's aircraft duopoly with Airbus.",
    moves: "Delivery rates, safety regulation, and its order backlog." },
  { symbol: "CAT", name: "Caterpillar Inc.", sector: "Heavy machinery",
    what: "Makes construction and mining equipment \u2014 a bellwether for global building activity.",
    moves: "Infrastructure spending and mining capital budgets." },
  { symbol: "GE", name: "GE Aerospace", sector: "Aerospace",
    what: "Builds and services jet engines, after splitting off its healthcare and energy arms.",
    moves: "Air traffic and lucrative engine servicing contracts." },
  { symbol: "F", name: "Ford Motor Company", sector: "Automotive",
    what: "Trucks (the F-150), commercial vans, and a loss-making but strategic EV division.",
    moves: "Truck demand, labour costs, and EV losses." },
  { symbol: "UBER", name: "Uber Technologies, Inc.", sector: "Mobility & delivery",
    what: "Ride-hailing and food delivery, plus a growing freight and advertising business.",
    moves: "Trip growth and driver supply costs." },
  { symbol: "ABNB", name: "Airbnb, Inc.", sector: "Travel",
    what: "A marketplace for short-term stays; it takes a cut of each booking rather than owning property.",
    moves: "Travel demand and city-by-city regulation." },
  { symbol: "SHOP", name: "Shopify Inc.", sector: "E-commerce software",
    what: "Software that lets merchants run their own online stores, plus payments and logistics tools.",
    moves: "Merchant sales volume \u2014 it earns a slice of what they sell." },
  { symbol: "SQ", name: "Block, Inc.", sector: "Payments & fintech",
    what: "Square card readers for small businesses and the Cash App consumer wallet, plus bitcoin services.",
    moves: "Cash App user growth and small-business health." },
  { symbol: "PYPL", name: "PayPal Holdings, Inc.", sector: "Payments",
    what: "Online checkout, Venmo, and Braintree's payment processing behind the scenes.",
    moves: "Transaction margins under pressure from newer rivals." },
  { symbol: "HOOD", name: "Robinhood Markets, Inc.", sector: "Brokerage",
    what: "A commission-free trading app for stocks, options and crypto, earning mostly from order flow and interest.",
    moves: "Retail trading activity and crypto volume." },
  { symbol: "SOFI", name: "SoFi Technologies, Inc.", sector: "Digital banking",
    what: "An online bank that started in student loans and now offers accounts, investing and lending.",
    moves: "Deposit growth and loan credit quality." },
  { symbol: "RBLX", name: "Roblox Corporation", sector: "Gaming platform",
    what: "A platform where users build and play each other's games, monetised through its Robux currency.",
    moves: "Daily users and hours engaged, mostly younger players." },
  { symbol: "RDDT", name: "Reddit, Inc.", sector: "Social media",
    what: "The forum network of subreddits, earning from advertising and from licensing its text to AI companies.",
    moves: "User growth and AI data-licensing deals." },
  { symbol: "ARM", name: "Arm Holdings plc", sector: "Semiconductor IP",
    what: "Designs the chip architecture almost every smartphone uses, and licenses it out rather than manufacturing.",
    moves: "Royalty rates and its push into data-centre chips." },
  { symbol: "DELL", name: "Dell Technologies Inc.", sector: "Computer hardware",
    what: "PCs, servers and storage, now selling AI server racks to data centres.",
    moves: "AI server orders against thin hardware margins." },
  { symbol: "MRVL", name: "Marvell Technology, Inc.", sector: "Semiconductors",
    what: "Makes networking and custom silicon that moves data inside data centres.",
    moves: "Custom AI chip programmes with hyperscale customers." },
  { symbol: "QCOM", name: "QUALCOMM Incorporated", sector: "Semiconductors",
    what: "Smartphone processors and the modem patents most phones must license.",
    moves: "Phone sales and its licensing disputes." },
  { symbol: "TXN", name: "Texas Instruments Incorporated", sector: "Semiconductors",
    what: "Analog chips \u2014 the unglamorous components inside cars, factories and appliances.",
    moves: "Industrial and automotive demand cycles." },
  { symbol: "CSCO", name: "Cisco Systems, Inc.", sector: "Networking",
    what: "Routers, switches and security software that carry enterprise and internet traffic.",
    moves: "Enterprise network upgrade cycles." },
  { symbol: "IBM", name: "International Business Machines Corporation", sector: "Enterprise IT",
    what: "Consulting, mainframes, hybrid cloud (Red Hat) and quantum computing research.",
    moves: "Software and consulting growth against a shrinking legacy base." },
  { symbol: "NOW", name: "ServiceNow, Inc.", sector: "Enterprise software",
    what: "Workflow software that automates IT, HR and customer service tickets inside large companies.",
    moves: "Subscription renewals and large enterprise deals." },
  { symbol: "INTU", name: "Intuit Inc.", sector: "Financial software",
    what: "TurboTax, QuickBooks, Credit Karma and Mailchimp \u2014 small business and consumer finance software.",
    moves: "Tax season results and small-business formation." },
  { symbol: "PANW", name: "Palo Alto Networks, Inc.", sector: "Cybersecurity",
    what: "Firewalls and cloud security for large organisations.",
    moves: "Security budgets, which tend to survive cost cutting." },
  { symbol: "CRWD", name: "CrowdStrike Holdings, Inc.", sector: "Cybersecurity",
    what: "Cloud-delivered software that protects laptops and servers from attack.",
    moves: "Subscription growth and its reputation after outages." },
  { symbol: "SNOW", name: "Snowflake Inc.", sector: "Data cloud",
    what: "A cloud data warehouse companies use to store and query enormous datasets.",
    moves: "Consumption \u2014 customers pay for what they run, so usage is revenue." },
  { symbol: "DDOG", name: "Datadog, Inc.", sector: "Software monitoring",
    what: "Watches whether other companies' software and infrastructure is healthy.",
    moves: "Cloud usage growth among its customers." },
  { symbol: "NET", name: "Cloudflare, Inc.", sector: "Internet infrastructure",
    what: "A global network that speeds up and protects websites, and increasingly runs code at the edge.",
    moves: "Large enterprise contracts and developer adoption." },
  { symbol: "SPOT", name: "Spotify Technology S.A.", sector: "Music streaming",
    what: "The largest music streaming service, with podcasts and audiobooks layered on.",
    moves: "Subscriber growth and the royalties it owes labels." },
  { symbol: "TSM", name: "Taiwan Semiconductor Manufacturing Company", sector: "Semiconductor foundry",
    what: "Manufactures the chips that Apple, NVIDIA and AMD design \u2014 the most advanced foundry in the world.",
    moves: "Leading-edge capacity, AI demand, and Taiwan geopolitics." },
  { symbol: "ASML", name: "ASML Holding N.V.", sector: "Semiconductor equipment",
    what: "The only company making EUV lithography machines \u2014 no advanced chip exists without them.",
    moves: "Machine orders and export restrictions to China." },
  { symbol: "BABA", name: "Alibaba Group Holding Limited", sector: "E-commerce & cloud",
    what: "China's largest e-commerce group (Taobao, Tmall) plus its cloud division.",
    moves: "Chinese consumer spending and Beijing's regulatory mood." },
  { symbol: "MELI", name: "MercadoLibre, Inc.", sector: "E-commerce & fintech",
    what: "Latin America's dominant online marketplace, with Mercado Pago payments attached.",
    moves: "Regional growth and currency instability." },
  { symbol: "WFC", name: "Wells Fargo & Company", sector: "Banking",
    what: "A large US consumer and commercial bank, long constrained by regulatory penalties.",
    moves: "Rates, and relief from its regulatory asset cap." },
  { symbol: "MS", name: "Morgan Stanley", sector: "Investment banking & wealth",
    what: "Investment banking plus a very large wealth management arm managing client money.",
    moves: "Market levels \u2014 fee income tracks asset values." },
  { symbol: "C", name: "Citigroup Inc.", sector: "Banking",
    what: "A global bank with unusually large international and corporate treasury operations.",
    moves: "Its long restructuring and global rate spreads." },
  { symbol: "AXP", name: "American Express Company", sector: "Payments & lending",
    what: "Unlike Visa, it issues its own cards and lends \u2014 earning fees and interest from affluent spenders.",
    moves: "Affluent consumer spending and travel." },
  { symbol: "ABBV", name: "AbbVie Inc.", sector: "Pharmaceuticals",
    what: "Immunology drugs Skyrizi and Rinvoq, plus Botox, after Humira lost exclusivity.",
    moves: "How fast newer drugs replace Humira's lost revenue." },
  { symbol: "MRK", name: "Merck & Co., Inc.", sector: "Pharmaceuticals",
    what: "Best known for Keytruda, the leading cancer immunotherapy.",
    moves: "Keytruda's patent cliff and the pipeline behind it." },
  { symbol: "PFE", name: "Pfizer Inc.", sector: "Pharmaceuticals",
    what: "Vaccines and medicines, still normalising after its COVID-era boom.",
    moves: "Pipeline results and post-pandemic revenue decline." },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc.", sector: "Life sciences tools",
    what: "Sells the instruments and reagents laboratories use \u2014 a supplier to the whole industry.",
    moves: "Pharma research budgets." },
  { symbol: "NKE", name: "NIKE, Inc.", sector: "Apparel & footwear",
    what: "The largest athletic footwear and apparel brand, shifting toward selling direct to consumers.",
    moves: "Wholesale orders and China demand." },
  { symbol: "SBUX", name: "Starbucks Corporation", sector: "Restaurants",
    what: "The global coffeehouse chain, with a huge mobile ordering and rewards business.",
    moves: "Same-store sales and China's recovery." },
  { symbol: "LOW", name: "Lowe's Companies, Inc.", sector: "Retail",
    what: "The second-largest home-improvement chain, weighted toward DIY customers.",
    moves: "Home renovation demand and rates." },
  { symbol: "TGT", name: "Target Corporation", sector: "Retail",
    what: "A general merchandise retailer leaning on apparel and home goods more than groceries.",
    moves: "Discretionary spending, which swings with sentiment." },
  { symbol: "T", name: "AT&T Inc.", sector: "Telecommunications",
    what: "US mobile and fibre broadband, after shedding its media ambitions.",
    moves: "Subscriber additions and its dividend's safety." },
  { symbol: "VZ", name: "Verizon Communications Inc.", sector: "Telecommunications",
    what: "A large US wireless carrier with a growing fibre and fixed-wireless business.",
    moves: "Phone subscriber churn and dividend coverage." },
  { symbol: "TMUS", name: "T-Mobile US, Inc.", sector: "Telecommunications",
    what: "The wireless carrier that grew fastest after the Sprint merger, with the deepest 5G spectrum.",
    moves: "Subscriber share gains from rivals." },
  { symbol: "GM", name: "General Motors Company", sector: "Automotive",
    what: "Chevrolet, GMC, Cadillac and Buick, plus the Cruise self-driving unit.",
    moves: "Truck and SUV margins, and EV losses." },
  { symbol: "RIVN", name: "Rivian Automotive, Inc.", sector: "Electric vehicles",
    what: "Builds electric trucks and SUVs, and delivery vans for Amazon.",
    moves: "Production ramp and how fast it burns cash." },
  { symbol: "DAL", name: "Delta Air Lines, Inc.", sector: "Airlines",
    what: "A major US airline, unusually reliant on premium cabins and its credit-card partnership.",
    moves: "Travel demand and jet fuel prices." },
  { symbol: "MAR", name: "Marriott International, Inc.", sector: "Hotels",
    what: "The largest hotel group \u2014 it franchises and manages brands rather than owning most buildings.",
    moves: "Room rates and business travel." },
  { symbol: "CVNA", name: "Carvana Co.", sector: "Auto retail",
    what: "Sells used cars entirely online, delivering them or dispensing them from vending-machine towers.",
    moves: "Used car prices and its heavy debt load." },
  { symbol: "AFRM", name: "Affirm Holdings, Inc.", sector: "Consumer lending",
    what: "Buy-now-pay-later loans offered at online checkout.",
    moves: "Consumer credit quality and funding costs." },
  { symbol: "DASH", name: "DoorDash, Inc.", sector: "Delivery",
    what: "The largest US food-delivery platform, expanding into groceries and retail.",
    moves: "Order frequency and its take rate per delivery." },
  { symbol: "SPY", name: "SPDR S&P 500 ETF Trust", sector: "US large-cap ETF",
    what: "One share holds a slice of all 500 companies in the S&P 500 \u2014 the broadest single bet on the US market. The oldest and most traded ETF in existence.",
    moves: "The US economy in aggregate; it IS the market benchmark." },
  { symbol: "QQQ", name: "Invesco QQQ Trust", sector: "US tech ETF",
    what: "Holds the 100 largest non-financial Nasdaq companies \u2014 very concentrated in big tech.",
    moves: "Technology earnings and interest rates." },
  { symbol: "IWM", name: "iShares Russell 2000 ETF", sector: "US small-cap ETF",
    what: "Holds two thousand smaller US companies. Small caps swing harder than large ones, in both directions.",
    moves: "Domestic economic health and credit conditions." },
  { symbol: "DIA", name: "SPDR Dow Jones Industrial Average ETF", sector: "US blue-chip ETF",
    what: "Tracks the 30 companies of the Dow \u2014 weighted by share price, an old-fashioned quirk.",
    moves: "Large industrial and consumer names." },
  { symbol: "VTI", name: "Vanguard Total Stock Market ETF", sector: "Total US market ETF",
    what: "Holds essentially every publicly traded US company, large and small, in one fund.",
    moves: "The entire US equity market." },
  { symbol: "GLD", name: "SPDR Gold Shares", sector: "Commodity ETF",
    what: "Holds physical gold bullion in a vault; one share is a small fraction of an ounce.",
    moves: "Real interest rates, the dollar, and fear." },
  { symbol: "SLV", name: "iShares Silver Trust", sector: "Commodity ETF",
    what: "Holds physical silver \u2014 part precious metal, part industrial input, so it moves more violently than gold.",
    moves: "Industrial demand and precious-metal sentiment." },
  { symbol: "USO", name: "United States Oil Fund", sector: "Commodity ETF",
    what: "Tracks crude oil using futures contracts, which means it can drift from the spot price over time.",
    moves: "Oil prices and the shape of the futures curve." },
  { symbol: "TLT", name: "iShares 20+ Year Treasury Bond ETF", sector: "Bond ETF",
    what: "Holds long-dated US government bonds. It rises when interest rates fall and falls when they rise.",
    moves: "Long-term interest rates \u2014 its whole story." },
  { symbol: "ARKK", name: "ARK Innovation ETF", sector: "Thematic ETF",
    what: "An actively managed fund concentrated in speculative, high-growth technology bets.",
    moves: "Risk appetite; it amplifies both booms and busts." },
  { symbol: "SMH", name: "VanEck Semiconductor ETF", sector: "Sector ETF",
    what: "Holds the largest chipmakers \u2014 NVIDIA, TSMC, Broadcom and peers \u2014 in one basket.",
    moves: "The semiconductor cycle and AI spending." },
  { symbol: "VOO", name: "Vanguard S&P 500 ETF", sector: "US large-cap ETF",
    what: "The same S&P 500 as SPY, at one of the lowest fees available.",
    moves: "The US market; the difference from SPY is cost, not holdings." },
  { symbol: "SCHD", name: "Schwab U.S. Dividend Equity ETF", sector: "Dividend ETF",
    what: "Screens for established US companies with a long record of paying dividends.",
    moves: "Rates and the appeal of income versus growth." },
  { symbol: "XLK", name: "Technology Select Sector SPDR Fund", sector: "Sector ETF",
    what: "The technology slice of the S&P 500 in one fund.",
    moves: "Big-tech earnings." },
  { symbol: "XLF", name: "Financial Select Sector SPDR Fund", sector: "Sector ETF",
    what: "Banks, insurers and asset managers from the S&P 500.",
    moves: "Interest rates and credit conditions." },
  { symbol: "XLE", name: "Energy Select Sector SPDR Fund", sector: "Sector ETF",
    what: "The S&P 500's oil and gas producers and servicers.",
    moves: "Crude oil and natural gas prices." },
  { symbol: "XLV", name: "Health Care Select Sector SPDR Fund", sector: "Sector ETF",
    what: "Pharma, insurers and device makers from the S&P 500.",
    moves: "Drug pipelines and health policy." },
  { symbol: "XLY", name: "Consumer Discretionary Select Sector SPDR", sector: "Sector ETF",
    what: "The things people buy when they feel comfortable \u2014 cars, restaurants, retail. Amazon and Tesla dominate it.",
    moves: "Consumer confidence and spending." },
  { symbol: "XLI", name: "Industrial Select Sector SPDR Fund", sector: "Sector ETF",
    what: "Machinery, aerospace, railways and logistics.",
    moves: "Manufacturing activity and infrastructure spending." },
  { symbol: "EEM", name: "iShares MSCI Emerging Markets ETF", sector: "International ETF",
    what: "Stocks from developing economies \u2014 China, India, Taiwan, Brazil and others.",
    moves: "The dollar, global growth, and China." },
  { symbol: "EFA", name: "iShares MSCI EAFE ETF", sector: "International ETF",
    what: "Developed markets outside North America: Europe, Australasia and the Far East.",
    moves: "Foreign currencies and non-US growth." },
  { symbol: "VNQ", name: "Vanguard Real Estate ETF", sector: "Real estate ETF",
    what: "Holds REITs \u2014 companies that own income-producing property and must pay out most profits.",
    moves: "Interest rates and property occupancy." },
  { symbol: "HYG", name: "iShares iBoxx High Yield Corporate Bond ETF", sector: "Bond ETF",
    what: "Holds 'junk' bonds \u2014 debt from companies with weaker credit, paying higher interest for the risk.",
    moves: "Credit spreads; it falls when investors fear defaults." },
  { symbol: "AGG", name: "iShares Core U.S. Aggregate Bond ETF", sector: "Bond ETF",
    what: "A broad basket of investment-grade US bonds \u2014 government, corporate and mortgage.",
    moves: "Interest rates across the whole curve." },
  { symbol: "TQQQ", name: "ProShares UltraPro QQQ", sector: "Leveraged ETF",
    what: "Aims for THREE TIMES the Nasdaq-100's move each DAY. Because it resets daily, it decays in choppy markets \u2014 it is a tool for days, not years.",
    moves: "Nasdaq moves, magnified \u2014 and time itself works against you." },
  { symbol: "SQQQ", name: "ProShares UltraPro Short QQQ", sector: "Inverse leveraged ETF",
    what: "Aims for MINUS three times the Nasdaq-100's daily move \u2014 it gains when tech falls. Decay is brutal over time.",
    moves: "Nasdaq declines, magnified; holding it long is usually a loss." },
  { symbol: "SOXL", name: "Direxion Daily Semiconductor Bull 3X", sector: "Leveraged ETF",
    what: "Three times the daily move of a semiconductor index \u2014 among the most volatile funds listed.",
    moves: "Chip stocks, magnified threefold each day." },
  { symbol: "GDX", name: "VanEck Gold Miners ETF", sector: "Sector ETF",
    what: "Holds gold mining companies, which amplify gold's moves because their costs are fixed.",
    moves: "Gold prices, leveraged by mining economics." },
  { symbol: "BITO", name: "ProShares Bitcoin Strategy ETF", sector: "Crypto futures ETF",
    what: "Tracks bitcoin through futures contracts rather than holding coins, so it can drift from spot.",
    moves: "Bitcoin's price and futures roll costs." },
  { symbol: "BTC/USD", name: "Bitcoin", sector: "Cryptocurrency",
    what: "The first and largest cryptocurrency. No company, no earnings, no board \u2014 its price is supply, demand and conviction. Supply is capped at 21 million coins.",
    moves: "Institutional adoption, rates, and its four-year halving cycle." },
  { symbol: "ETH/USD", name: "Ethereum", sector: "Cryptocurrency",
    what: "The network most crypto applications are built on. Its coin, ether, pays the fees to run programs on that network.",
    moves: "On-chain activity and staking economics." },
  { symbol: "SOL/USD", name: "Solana", sector: "Cryptocurrency",
    what: "A fast, cheap blockchain competing with Ethereum, popular for trading apps and consumer tokens.",
    moves: "Network usage \u2014 and its history of outages." },
  { symbol: "XRP/USD", name: "XRP", sector: "Cryptocurrency",
    what: "A token designed for moving money between institutions quickly and cheaply.",
    moves: "Bank adoption and its long US legal history." },
  { symbol: "DOGE/USD", name: "Dogecoin", sector: "Cryptocurrency",
    what: "Started as a joke about crypto speculation and became a real, heavily traded market. Unlimited supply.",
    moves: "Sentiment and celebrity attention more than fundamentals." },
  { symbol: "AVAX/USD", name: "Avalanche", sector: "Cryptocurrency",
    what: "A blockchain platform emphasising speed and custom sub-networks for institutions.",
    moves: "Developer adoption and its subnet strategy." },
  { symbol: "LINK/USD", name: "Chainlink", sector: "Cryptocurrency",
    what: "An 'oracle' network that feeds real-world data, like prices, into blockchain contracts.",
    moves: "How much value depends on its data feeds." },
  { symbol: "DOT/USD", name: "Polkadot", sector: "Cryptocurrency",
    what: "A network designed to let separate blockchains talk to each other.",
    moves: "Parachain activity and cross-chain demand." },
  { symbol: "LTC/USD", name: "Litecoin", sector: "Cryptocurrency",
    what: "One of the oldest bitcoin alternatives, built for faster, cheaper payments.",
    moves: "Payment usage and bitcoin's direction." },
  { symbol: "BCH/USD", name: "Bitcoin Cash", sector: "Cryptocurrency",
    what: "A 2017 split from bitcoin that chose larger blocks to make everyday payments cheaper.",
    moves: "Bitcoin's direction and its own niche adoption." },
  { symbol: "UNI/USD", name: "Uniswap", sector: "Cryptocurrency",
    what: "The token of the largest decentralised exchange, where trades happen without a company in the middle.",
    moves: "Trading volume on the protocol and governance decisions." },
  { symbol: "AAVE/USD", name: "Aave", sector: "Cryptocurrency",
    what: "The token of a lending protocol where people borrow and lend crypto without a bank.",
    moves: "Total value deposited and lending rates." },
  { symbol: "SHIB/USD", name: "Shiba Inu", sector: "Cryptocurrency",
    what: "A meme token with an enormous supply, which is why each unit costs a tiny fraction of a cent.",
    moves: "Retail enthusiasm; there is little underlying to value." },
  { symbol: "MKR/USD", name: "Maker", sector: "Cryptocurrency",
    what: "Governs the DAI stablecoin system \u2014 holders vote on the rules that keep DAI near one dollar.",
    moves: "DAI demand and protocol revenue." },
  { symbol: "CRV/USD", name: "Curve DAO", sector: "Cryptocurrency",
    what: "Governs an exchange specialised in swapping stablecoins with very low slippage.",
    moves: "Stablecoin trading volume." },
  { symbol: "GRT/USD", name: "The Graph", sector: "Cryptocurrency",
    what: "Pays a network to index blockchain data so applications can query it quickly.",
    moves: "Developer demand for indexed data." },
  { symbol: "XTZ/USD", name: "Tezos", sector: "Cryptocurrency",
    what: "A blockchain that upgrades itself through on-chain voting rather than contentious splits.",
    moves: "Governance activity and adoption." },
  { symbol: "BAT/USD", name: "Basic Attention Token", sector: "Cryptocurrency",
    what: "Rewards users of the Brave browser for viewing privacy-respecting ads.",
    moves: "Brave's user growth and advertiser interest." },
  { symbol: "SPX", name: "S&P 500 Index", sector: "US large-cap index",
    what: "The number itself \u2014 a measure of 500 large US companies, weighted by market value. You cannot buy the index; trade SPY or its futures instead.",
    moves: "The broad US market." },
  { symbol: "NDX", name: "Nasdaq-100 Index", sector: "US tech index",
    what: "Measures the 100 largest non-financial Nasdaq companies. Trade it through QQQ or futures.",
    moves: "Big technology." },
  { symbol: "COMP", name: "Nasdaq Composite Index", sector: "US index",
    what: "Measures roughly all 3,000+ companies listed on the Nasdaq exchange.",
    moves: "Technology and growth stocks broadly." },
  { symbol: "DJI", name: "Dow Jones Industrial Average", sector: "US blue-chip index",
    what: "Thirty large US companies, weighted by share price rather than size \u2014 an old convention that still moves headlines.",
    moves: "Large industrials and consumer names." },
  { symbol: "RUT", name: "Russell 2000 Index", sector: "US small-cap index",
    what: "Measures two thousand smaller US companies \u2014 the domestic economy's temperature.",
    moves: "Small business conditions and credit." },
  { symbol: "VIX", name: "CBOE Volatility Index", sector: "Volatility index",
    what: "The market's fear gauge: how much movement traders EXPECT in the S&P 500 over the next 30 days, derived from option prices. It spikes when stocks fall.",
    moves: "Fear itself \u2014 it usually rises when the market drops." },
  { symbol: "UVIX", name: "2x Long VIX Futures ETF", sector: "Volatility ETF",
    what: "Doubles the daily move of short-term VIX futures. It decays relentlessly \u2014 a hedge measured in days.",
    moves: "Volatility spikes, magnified, minus heavy decay." },
  { symbol: "VXX", name: "iPath Series B S&P 500 VIX Short-Term Futures", sector: "Volatility ETN",
    what: "Tracks short-dated VIX futures. It reliably grinds lower over time because those futures usually cost more than spot.",
    moves: "Fear spikes; it loses value in calm markets by design." },
  { symbol: "SPXL", name: "Direxion Daily S&P 500 Bull 3X", sector: "Leveraged ETF",
    what: "Three times the S&P 500's daily move, reset every day.",
    moves: "The index, magnified \u2014 and decay in choppy markets." },
  { symbol: "QLD", name: "ProShares Ultra QQQ", sector: "Leveraged ETF",
    what: "Two times the Nasdaq-100's daily move.",
    moves: "Nasdaq direction, doubled daily." },
  { symbol: "JEPI", name: "JPMorgan Equity Premium Income ETF", sector: "Income ETF",
    what: "Owns large US stocks and sells options against them to generate monthly income, trading away some upside.",
    moves: "Volatility (which raises option income) and the market's direction." },
  { symbol: "JEPQ", name: "JPMorgan Nasdaq Equity Premium Income ETF", sector: "Income ETF",
    what: "The Nasdaq version of JEPI \u2014 tech stocks plus written options for monthly income.",
    moves: "Tech volatility and option premiums." },
  { symbol: "QYLD", name: "Global X Nasdaq 100 Covered Call ETF", sector: "Income ETF",
    what: "Sells call options on the Nasdaq-100 every month, paying out the premium as income and capping gains.",
    moves: "Option premiums; it lags badly in strong rallies." },
  { symbol: "VYM", name: "Vanguard High Dividend Yield ETF", sector: "Dividend ETF",
    what: "Holds US companies with above-average dividend yields.",
    moves: "Rates and the appeal of income." },
  { symbol: "DVY", name: "iShares Select Dividend ETF", sector: "Dividend ETF",
    what: "Screens for US companies with sustained dividend payment records.",
    moves: "Rates and payout durability." },
  { symbol: "IEF", name: "iShares 7-10 Year Treasury Bond ETF", sector: "Bond ETF",
    what: "Holds intermediate US government bonds \u2014 less rate-sensitive than TLT.",
    moves: "Medium-term interest rates." },
  { symbol: "SHY", name: "iShares 1-3 Year Treasury Bond ETF", sector: "Bond ETF",
    what: "Short-dated government bonds \u2014 close to cash, barely moved by rate changes.",
    moves: "Front-end rates; it is the calm end of the bond market." },
  { symbol: "LQD", name: "iShares iBoxx Investment Grade Corporate Bond", sector: "Bond ETF",
    what: "Holds bonds from financially solid companies \u2014 safer than HYG, lower yielding.",
    moves: "Rates and corporate credit spreads." },
  { symbol: "TIP", name: "iShares TIPS Bond ETF", sector: "Bond ETF",
    what: "Inflation-protected US government bonds; their principal rises with the consumer price index.",
    moves: "Real yields and inflation expectations." },
  { symbol: "XLP", name: "Consumer Staples Select Sector SPDR", sector: "Sector ETF",
    what: "The things people buy regardless of the economy \u2014 food, drinks, household goods.",
    moves: "Defensive rotation; it holds up when growth scares markets." },
  { symbol: "XLU", name: "Utilities Select Sector SPDR Fund", sector: "Sector ETF",
    what: "Electric and gas utilities \u2014 steady, regulated, dividend-heavy, and now an AI power story.",
    moves: "Interest rates and data-centre electricity demand." },
  { symbol: "XLB", name: "Materials Select Sector SPDR Fund", sector: "Sector ETF",
    what: "Chemicals, metals and packaging companies.",
    moves: "Industrial demand and commodity prices." },
  { symbol: "XLC", name: "Communication Services Select Sector SPDR", sector: "Sector ETF",
    what: "Alphabet, Meta, Netflix and the telecoms \u2014 media and communications.",
    moves: "Advertising spending and big-tech results." },
  { symbol: "XLRE", name: "Real Estate Select Sector SPDR Fund", sector: "Sector ETF",
    what: "The S&P 500's real estate investment trusts.",
    moves: "Interest rates above all." },
  { symbol: "IBIT", name: "iShares Bitcoin Trust", sector: "Crypto ETF",
    what: "Holds actual bitcoin in custody \u2014 spot exposure through a normal brokerage account.",
    moves: "Bitcoin's price, near one-for-one." },
  { symbol: "FBTC", name: "Fidelity Wise Origin Bitcoin Fund", sector: "Crypto ETF",
    what: "Fidelity's spot bitcoin fund, holding coins directly.",
    moves: "Bitcoin's price." },
  { symbol: "ETHA", name: "iShares Ethereum Trust", sector: "Crypto ETF",
    what: "Holds ether directly for investors who want it in a brokerage account.",
    moves: "Ethereum's price." },
  { symbol: "NVO", name: "Novo Nordisk A/S", sector: "Pharmaceuticals",
    what: "The Danish maker of Ozempic and Wegovy \u2014 Eli Lilly's main rival in weight-loss drugs.",
    moves: "Obesity drug supply and competition." },
  { symbol: "SAP", name: "SAP SE", sector: "Enterprise software",
    what: "Germany's enterprise resource planning giant \u2014 the software large manufacturers run on.",
    moves: "Cloud migration of its old on-premise customers." },
  { symbol: "SONY", name: "Sony Group Corporation", sector: "Consumer electronics & media",
    what: "PlayStation, camera sensors, music and film studios.",
    moves: "Console cycles and image-sensor demand." },
  { symbol: "TM", name: "Toyota Motor Corporation", sector: "Automotive",
    what: "The world's largest carmaker by volume, with a hybrid-first strategy rather than a pure EV one.",
    moves: "Global vehicle demand and the yen." },
  { symbol: "HSBC", name: "HSBC Holdings plc", sector: "Banking",
    what: "A British bank whose profits come mostly from Asia, especially Hong Kong.",
    moves: "Asian rates and China's property market." },
  { symbol: "SHEL", name: "Shell plc", sector: "Oil & gas",
    what: "European integrated oil major with a large liquefied natural gas business.",
    moves: "Oil, gas and LNG prices." },
  { symbol: "BP", name: "BP p.l.c.", sector: "Oil & gas",
    what: "British integrated oil company, oscillating between energy transition and oil investment.",
    moves: "Crude prices and strategy shifts." },
  { symbol: "RIO", name: "Rio Tinto Group", sector: "Mining",
    what: "One of the largest miners of iron ore, copper and aluminium.",
    moves: "Chinese construction demand and metal prices." },
  { symbol: "BHP", name: "BHP Group Limited", sector: "Mining",
    what: "The world's biggest mining company by value \u2014 iron ore, copper, coal.",
    moves: "Commodity prices and Chinese steel output." },
  { symbol: "PDD", name: "PDD Holdings Inc.", sector: "E-commerce",
    what: "Owns Pinduoduo in China and Temu internationally \u2014 aggressive discount marketplaces.",
    moves: "Temu's international expansion and Chinese consumers." },
  { symbol: "JD", name: "JD.com, Inc.", sector: "E-commerce",
    what: "A Chinese online retailer that owns its logistics network, unlike marketplace-only rivals.",
    moves: "Chinese consumer spending." },
  { symbol: "NIO", name: "NIO Inc.", sector: "Electric vehicles",
    what: "A Chinese EV maker known for battery-swap stations instead of only charging.",
    moves: "Chinese EV competition and cash burn." },
  { symbol: "INFY", name: "Infosys Limited", sector: "IT services",
    what: "Indian technology consulting and outsourcing at global scale.",
    moves: "Western IT budgets and the rupee." },
  { symbol: "O", name: "Realty Income Corporation", sector: "Real estate (REIT)",
    what: "Owns thousands of single-tenant retail properties and pays dividends monthly.",
    moves: "Interest rates and tenant credit quality." },
  { symbol: "MAIN", name: "Main Street Capital Corporation", sector: "Business development",
    what: "Lends to and invests in mid-sized private US companies, paying monthly dividends.",
    moves: "Credit conditions for smaller businesses." },
  { symbol: "PFF", name: "iShares Preferred & Income Securities ETF", sector: "Income ETF",
    what: "Holds preferred shares \u2014 hybrids that pay fixed dividends and rank above common stock.",
    moves: "Interest rates and issuer credit." },
  { symbol: "MO", name: "Altria Group, Inc.", sector: "Tobacco",
    what: "Sells Marlboro in the United States; a declining volume business managed for cash and dividends.",
    moves: "Cigarette volumes and regulation." },
  { symbol: "PM", name: "Philip Morris International Inc.", sector: "Tobacco",
    what: "Sells tobacco outside the US, pushing hard into heated products like IQOS and Zyn.",
    moves: "The shift from cigarettes to smoke-free products." },
];

/** Symbol → profile, for O(1) lookup by the display ticker. */
export const INSTRUMENT_BY_SYMBOL = new Map(
  INSTRUMENTS.map((i) => [i.symbol.toUpperCase(), i]),
);

/** The board sends prefixed symbols (IDX:SPX); the catalog is keyed by
    what a human calls the thing. */
export function instrumentFor(symbol: string): Instrument | undefined {
  const u = symbol.toUpperCase();
  return INSTRUMENT_BY_SYMBOL.get(u.replace(/^(IDX|FX|FUT):/, ""))
      ?? INSTRUMENT_BY_SYMBOL.get(u);
}
