import type { Track } from "./types";

/*
  Stage 11 — The Wider Universe. The instruments the desk just gained: foreign
  companies bought through a bank's receipt (ADRs), whole countries wrapped in
  one ticker, the rung between debt and equity (preferreds), funds whose price
  wanders away from what they hold (closed-end funds), and currencies — which
  only ever trade in pairs.

  These map to the board's Global, Income and FX sections. A learner who can
  buy them from the terminal should be able to explain what they are, what they
  cost, and how each one fails. That last part is the point of the stage.
*/

export const worldStage: Track = {
  id: "s11-world",
  title: "The Wider Universe",
  tagline: "Foreign companies, whole countries, the rung between debt and equity, funds priced away from their worth, and currencies that only trade in pairs.",
  covers: "ADRs, funds, preferreds & FX",
  accent: "agent",
  lessons: [
    // ---------------------------------------------------------------
    {
      id: "w1-adrs",
      title: "ADRs: owning a foreign company from a US account",
      hook: "The shares are in a vault in São Paulo. What changes hands in New York is a bank's receipt for them.",
      minutes: 14,
      xp: 90,
      sections: [
        { kind: "analogy", title: "A coat check for foreign shares",
          text: "The coat is in a cloakroom in another country. You hold the ticket, and the ticket is what trades here — in dollars, during New York hours. The coat never moves. The cloakroom charges a small fee for holding it, and if the country the coat is in has a bad year, your ticket is worth less even though the coat is exactly where you left it." },
        { kind: "prose", text: "An ADR — American Depositary Receipt — is a US-listed security that represents shares of a company listed somewhere else. A depositary bank (the institution that holds the foreign shares and issues receipts against them) buys ordinary shares on the home exchange, parks them with a local custodian, and issues receipts here. You buy the receipt through an ordinary US account: dollars in, no foreign brokerage, no currency conversion of your own. ABEV, the receipt for the Brazilian brewer Ambev, works exactly this way. One receipt is not always one home share — every program sets a ratio, and a receipt might represent one share, or ten, or a tenth of one. Check it before you compare any per-share number you read about the company." },
        { kind: "keyIdea", title: "You own a claim on the share, not the share",
          text: "The depositary is between you and the company. Dividends reach you after the bank converts them to dollars and takes its cut. Voting rights pass through the bank if they pass through at all, and often late. Corporate actions arrive translated and second-hand. The terms live in a document called the deposit agreement, which you did not sign and which the bank can amend. None of this makes ADRs bad; it makes them a wrapper, and wrappers have terms." },
        { kind: "formula", label: "What an ADR should be worth", expression: "ADR fair value ≈ (home share price ÷ FX rate) × home shares per receipt",
          legend: "If a home share costs 15 reais and a dollar buys 5 reais, one share is worth $3 — so a receipt representing two shares belongs near $6. Professionals who can convert receipts into shares and back keep the two prices close, but only while both markets are open and conversion is actually permitted." },
        { kind: "prose", text: "That word 'approximately' is doing real work. The two prices drift because the two markets are rarely awake at the same time: São Paulo and Tokyo are shut for most of the US session, so the ADR trades on news the home listing hasn't priced yet, and the gap reconciles at the next home open. It also drifts when conversion gets expensive or restricted — some countries limit how freely capital crosses the border, and an arbitrage nobody can perform is an arbitrage that doesn't close. So the receipt's price is the home price, plus a currency, plus a time zone, plus friction." },
        { kind: "keyIdea", title: "A currency bet you never placed",
          text: "Suppose the home shares do nothing at all in their own currency for a month, and that currency falls 8% against the dollar. Your dollar-priced receipt falls about 8%. Buying a Brazilian brewer means taking a position in the real whether or not you have any view on the real. That isn't automatically bad — but a risk you didn't choose is a risk you didn't size, and unsized risk is how portfolios surprise their owners." },
        { kind: "chart", variant: "spread",
          caption: "Toggle to Thin. A great many receipts — especially the ones no company sponsors — trade like this: a wide gap, small size resting on each side. You pay that gap going in and again coming out, before the business has done anything at all." },
        { kind: "prose", text: "That distinction has a name. A sponsored ADR is one the foreign company itself arranged, with a single depositary bank and a legal agreement behind it; these are the receipts that list on the NYSE or Nasdaq and file financials with US regulators. An unsponsored ADR is created by a bank without the company's participation — occasionally several competing programs on the same company at once. Those trade over the counter, disclose less, trade thinner, and carry whatever terms the bank set. Same underlying business, materially worse container." },
        { kind: "keyIdea", title: "The fees that never show up as a red candle",
          text: "Three of them, all quiet. A depositary service fee — commonly a few cents per receipt per year — either netted out of a dividend or billed straight to the account. The bank's own exchange rate on every dividend it converts, which is rarely the best rate in the market. And foreign withholding tax, deducted at source by the company's home country before the money ever leaves it, at a rate set by that country and its tax treaty with the US. Individually trivial. Together, over years, the reason your return trails the company's." },
        { kind: "quiz",
          question: "A company's home-listed shares are flat all month in their local currency, and that currency falls 8% against the dollar. What most likely happened to the US-listed ADR?",
          choices: [
            "Flat as well — the receipt tracks the shares",
            "Down roughly 8% — your claim is on shares priced in a currency that lost value",
            "Up roughly 8%",
            "Nothing predictable — an ADR is unrelated to the home listing",
          ],
          answer: 1,
          explain: "The receipt is priced in dollars but backed by shares priced in another currency. Translate a flat local price through a currency that fell 8% and you get a dollar price about 8% lower. You held the company and the currency; only the currency moved." },
        { kind: "quiz",
          question: "Two receipts exist on the same foreign company: one sponsored and NYSE-listed, one unsponsored and trading over the counter. What is the honest difference?",
          choices: [
            "None — same company, so the same thing",
            "The unsponsored one was created without the company's involvement: thinner trading, less disclosure, terms set entirely by the bank",
            "The unsponsored one is cheaper to hold",
            "The sponsored one is guaranteed by the company",
          ],
          answer: 1,
          explain: "The business behind them is identical; the wrapper is not. An unsponsored program has no participation from the company, so disclosure is thinner, liquidity is worse, and the depositary writes the rules. Nothing about either is guaranteed by the company." },
        { kind: "desk", instruction: "Open ABEV — the US-listed receipt for a Brazilian brewer. Look at what you are actually seeing: a dollar price, quoted in New York hours, for a business that earns in reais and lists in São Paulo. Two of those three facts are the wrapper, not the company.", symbol: "ABEV" },
        { kind: "flashcards", title: "Depositary receipts",
          cards: [
            { front: "ADR", back: "A US-listed receipt representing shares of a company listed abroad." },
            { front: "Depositary bank", back: "The bank that holds the foreign shares and issues the receipts against them." },
            { front: "ADR ratio", back: "How many home shares one receipt represents — one, ten, or a fraction." },
            { front: "Sponsored vs unsponsored", back: "Arranged by the company (listed, disclosing) vs created by a bank alone (OTC, thinner)." },
            { front: "Depositary fee", back: "A few cents per receipt per year for custody — netted from dividends or billed direct." },
            { front: "Currency exposure", back: "You hold the company AND its home currency, whether or not you meant to." },
          ] },
      ],
    },

    // ---------------------------------------------------------------
    {
      id: "w2-country-funds",
      title: "Buying a country in one ticker",
      hook: "One symbol, a whole market. Just not quite the market you had in mind.",
      minutes: 14,
      xp: 90,
      sections: [
        { kind: "analogy", title: "A tour bus, not the country",
          text: "The bus takes you past the landmarks — the biggest listed companies, the famous exporters — and skips everything else: the private firms, the small caps nobody indexed, the parts of the economy that never listed shares at all. You have seen Japan. You have not seen Japan." },
        { kind: "prose", text: "A country or region fund is an ETF (a fund you buy like a stock) that holds a basket of one market's listed companies and wraps them in a US-listed, dollar-priced ticker. BBJP holds Japanese companies. ASHR tracks an index of mainland-listed Chinese companies — the A-shares that trade in Shanghai and Shenzhen, which foreign investors could barely touch for decades. EEM spreads across a couple of dozen emerging markets at once. One order, in dollars, from a normal account, and you have exposure to a market you cannot otherwise reach." },
        { kind: "keyIdea", title: "What's inside was somebody else's decision",
          text: "A country fund doesn't hold 'Japan.' It holds whatever an index rulebook says qualifies: a minimum size, a minimum free float (the portion of shares actually available to trade rather than locked up with founders or the state), a listing venue, sometimes a cap on any one name. Read the holdings before you form an opinion about the country. The label on the tin is a marketing decision; the contents are a rulebook." },
        { kind: "formula", label: "What you actually earn", expression: "your dollar return ≈ (1 + local market return) × (1 + currency return) − 1",
          legend: "Two engines, multiplied, not added. A market up 12% in its own currency, in a currency that fell 10% against the dollar: 1.12 × 0.90 = 1.008 — about +0.8%. You were right about the market and it barely paid." },
        { kind: "prose", text: "That is the first and largest reason a country fund's return is not the country's return. Unless the fund explicitly says it hedges the currency — and most of the plain ones don't — every point the local currency moves lands in your result. The prospectus says so in one line, and it is the single line worth finding. A hedged version of the same market is a genuinely different security with a different return and an extra cost." },
        { kind: "prose", text: "Three smaller wedges follow. Fees: the expense ratio comes out daily, and country funds are usually pricier than a broad domestic index fund. Withholding tax: many countries deduct a slice of dividends before the fund ever receives them. And hours: when Tokyo is closed and New York is open, the fund's price moves on expectations of what Tokyo will do tomorrow, so a US-session chart of a Japanese fund is partly a chart of American opinion about Japan." },
        { kind: "widget", variant: "correlation" },
        { kind: "keyIdea", title: "Concentration hiding inside diversification",
          text: "The widget above is the trap in miniature. Two hundred holdings sound like two hundred bets, but when they share one currency, one central bank, one government and often a handful of dominant exporters, they move as one line. Some country funds have a quarter of their money in five companies. You bought a market and received a sector, or sometimes a company — with the comforting word 'diversified' printed on the label." },
        { kind: "quiz",
          question: "A Japanese index rises 12% measured in yen. Over the same period the yen falls 10% against the dollar. Roughly what did an unhedged US investor earn?",
          choices: ["About +12%", "About +2%", "About +0.8%", "About −10%"],
          answer: 2,
          explain: "The two effects multiply: 1.12 × 0.90 = 1.008, so about +0.8% before fees. The market call was right and the currency ate essentially all of it. This is why 'the Nikkei was up' and 'my Japan fund was up' are different sentences." },
        { kind: "quiz",
          question: "A country fund holds 200 companies but its five largest positions are 30% of the fund. What does that tell you?",
          choices: [
            "It's well diversified — 200 names is plenty",
            "Its return will be driven disproportionately by a handful of companies, whatever the holding count suggests",
            "The fund is broken and should be avoided",
            "Nothing — weights don't matter",
          ],
          answer: 1,
          explain: "Diversification is about weights and independence, not the number of lines on a page. With 30% in five names, those five decide most of your outcome — and in many national markets they're in the same industry, exposed to the same currency and the same policy." },
        { kind: "desk", instruction: "Open BBJP, then look at ASHR. Two markets, two tickers, both priced in dollars during New York hours while their home exchanges are shut. Ask of each: what is inside it, what currency is it really exposed to, and who wrote the rulebook that chose the holdings.", symbol: "BBJP" },
        { kind: "flashcards", title: "Country & region funds",
          cards: [
            { front: "Country fund", back: "A US-listed ETF holding one market's listed companies, priced in dollars." },
            { front: "A-shares", back: "Companies listed on mainland Chinese exchanges — the market ASHR tracks." },
            { front: "Unhedged", back: "The fund takes the currency move straight into your return. Most plain country funds are." },
            { front: "Free float", back: "Shares actually available to trade — the basis most index weights use." },
            { front: "Expense ratio", back: "The fund's annual fee, deducted daily from the assets, whatever the return." },
            { front: "Return gap", back: "Local return × currency return, minus fees and withholding — not the headline index number." },
          ] },
      ],
    },

    // ---------------------------------------------------------------
    {
      id: "w3-preferred",
      title: "Preferred shares: the rung between debt and equity",
      hook: "It says 'share' on the label. It gets paid like a bond and behaves like one.",
      minutes: 14,
      xp: 90,
      sections: [
        { kind: "analogy", title: "The queue at the cashier's window",
          text: "When a company runs out of money, everyone lines up to be paid. Lenders and bondholders stand at the front. Preferred shareholders stand behind them. Common shareholders stand at the very back, and by the time the queue reaches them there is usually nothing left. Preferred is closer to the window than common — and still behind every single lender." },
        { kind: "prose", text: "A preferred share pays a fixed dividend, set as a rate on a par value (the face amount the security is issued and usually redeemed at, most often $25 for the ones sold to US retail investors). It ranks ahead of common shares for both dividends and whatever's left in a bankruptcy, and it normally carries no vote. In exchange for that seniority and that income, you give up the thing that makes common stock interesting: participation. If the company triples in value, the preferred still pays its fixed dividend and nothing more." },
        { kind: "formula", label: "What you're actually being paid", expression: "current yield = annual dividend ÷ price paid",
          legend: "A $25 preferred paying $1.50 a year yields 6% at par. Buy it at $20 and you're earning 7.5% on your money; buy it at $30 and you're earning 5%. The dividend never changed — only what you paid for it did." },
        { kind: "keyIdea", title: "It trades on interest rates, not on the story",
          text: "Because the payment is fixed, the price mostly moves opposite prevailing yields. If new issues start paying 8%, an old preferred paying 6% has to fall in price until its current yield competes — nobody pays par for the worse deal. This is why the company's common stock can double on a brilliant quarter while its preferred barely twitches. You are holding a bond-shaped payment with an equity-shaped position in the queue, and it will behave accordingly." },
        { kind: "keyIdea", title: "Callable: the issuer holds an option, and you sold it",
          text: "Most preferreds are callable — the issuer can redeem them at par, typically any time after about five years. Notice when they'll want to: when rates have fallen and they can refinance cheaper, which is exactly when your 6% looks attractive and has risen above par. So the moment your position works, it can be taken away at $25. Your upside is capped near the call price; your downside is not capped at all. Pay $28 for the yield and a call notice hands you a loss on the capital along with the end of the income." },
        { kind: "game", variant: "order-match", title: "Thin market, right order" },
        { kind: "prose", text: "That drill matters more here than almost anywhere. Individual preferred issues trade in tiny volume — a few thousand shares on a quiet day — and a market order into a book like that can fill cents away from where you looked. On a $25 security whose entire appeal is a 6% annual coupon, a 20-cent round-trip on execution is more than a month of income given away at the door. In illiquid securities, limit orders are not a preference; they're the whole discipline." },
        { kind: "prose", text: "Then the things that actually go wrong. A preferred dividend can be suspended without triggering a default, because it is a dividend and not interest — a cumulative preferred at least accrues the missed payments and must clear them before common gets a cent, while a non-cumulative one (common among bank issues) simply never pays them. Many preferreds are perpetual, with no maturity date to pull the price back to par, which makes them extremely sensitive to rates. And issuance is concentrated in banks, utilities and property companies, so a portfolio of 'diversified preferreds' is frequently a leveraged opinion about financials wearing an income costume." },
        { kind: "quiz",
          question: "Prevailing interest rates rise sharply. What most likely happens to an existing preferred share paying a fixed 6% on $25 par?",
          choices: [
            "It rises — higher rates mean higher income",
            "It falls, because its fixed payment must yield more to compete with newly issued securities",
            "Nothing — the dividend is fixed, so the price is fixed",
            "It follows the company's common stock",
          ],
          answer: 1,
          explain: "The payment can't change, so the price has to. If new issues pay 8%, the old 6% payment only attracts a buyer at a lower price — that's what makes its current yield competitive. Fixed income, floating price: rate sensitivity is the defining behavior of this instrument." },
        { kind: "quiz",
          question: "You paid $28 for a $25-par preferred to get its yield. Rates fall and the issuer calls it at par. What have you lost?",
          choices: [
            "Nothing — you get your money back",
            "$3 a share of capital, plus the income stream, exactly when comparable yields have dropped",
            "Only the dividend for that quarter",
            "It can't be called if you paid above par",
          ],
          answer: 1,
          explain: "A call pays par — $25 — regardless of your $28. You take a $3 capital loss and lose the payment, and you're reinvesting into the lower-rate world that motivated the call in the first place. Paying above par for yield is selling the issuer an option and being paid in coupons for it." },
        { kind: "desk", instruction: "On Markets, switch to the Income pill and open one of the listings there. Before anything else, find three numbers: the par value, the fixed dividend rate, and whether and when it can be called. Those three decide almost everything about how the security will behave." },
        { kind: "flashcards", title: "Preferred shares",
          cards: [
            { front: "Preferred share", back: "Fixed dividend, no vote, ranks above common and below all debt." },
            { front: "Par value", back: "The face amount — usually $25 — that the fixed rate is calculated on and calls are paid at." },
            { front: "Current yield", back: "Annual dividend ÷ price paid. Falls as you pay more." },
            { front: "Callable", back: "The issuer can redeem at par after a set date — usually when rates fall and it suits them." },
            { front: "Cumulative vs non-cumulative", back: "Missed dividends accrue and must be paid, vs simply never paid." },
            { front: "Rate sensitivity", back: "A fixed payment means the price moves opposite prevailing yields." },
          ] },
      ],
    },

    // ---------------------------------------------------------------
    {
      id: "w4-closed-end-funds",
      title: "Closed-end funds: where price and value part company",
      hook: "This fund publishes what it's worth every single day. The market ignores the number daily, and you can measure by how much.",
      minutes: 16,
      xp: 105,
      sections: [
        { kind: "analogy", title: "A boat with a fixed number of seats",
          text: "An ordinary fund adds a seat whenever someone wants one and removes it when they leave, so a ticket always costs what a seat is worth. A closed-end fund sold every seat once, at launch, and never printed another. To get on board you buy a seat from someone getting off, at whatever the two of you agree. The value of the ride and the price of the ticket are now free to disagree — and they do." },
        { kind: "prose", text: "A closed-end fund raises money once, lists on an exchange, and fixes its share count there. From that day the fund's shares trade between investors like any stock. Meanwhile the fund still publishes its NAV — net asset value, the market value of everything it holds divided by the shares outstanding — usually every day. So the same security carries two numbers: what it holds, and what people will pay for it. The second is under no obligation to equal the first." },
        { kind: "formula", label: "The gap, measured", expression: "premium / discount % = (market price − NAV) ÷ NAV × 100",
          legend: "Price $18, NAV $21: (18 − 21) ÷ 21 = −14%. A 14% discount. Positive means a premium — the market paying more than the holdings are worth. Both are ordinary and both can persist for years." },
        { kind: "keyIdea", title: "Price and value are not the same thing",
          text: "This is the most useful idea in markets, and closed-end funds are the one place it stops being philosophy. Everywhere else, arguing that something is 'worth' more or less than it trades for means arguing about the future. Here the fund tells you what it holds and what those holdings are worth, and the market publishes a different number next to it. A price is a vote about a thing, not a measurement of it. This instrument prints the difference every afternoon." },
        { kind: "prose", text: "Which raises the obvious question, and the obvious question has a disappointing answer. A 14% discount is not 14% of free money. You capture it only if it narrows while you hold, and it is under no obligation to narrow. Discounts persist for entirely rational reasons: fees high enough to justify paying less than the assets are worth, holdings so illiquid that the stated NAV is itself an estimate, borrowed money the market distrusts, a distribution policy that shrinks the fund, or a manager nobody wants to pay for. There is also no mechanism forcing convergence — unlike an ETF, nobody can create or redeem shares to arbitrage the gap away." },
        { kind: "calc", tool: "risk-reward", title: "Buying at a discount is a trade, not a gift" },
        { kind: "prose", text: "Frame it exactly as you'd frame any other trade: entry at the price, target somewhere toward NAV, and a stop where you admit the discount isn't closing. Set the target at NAV and you'll see the reward looks handsome — but the same widget forces the honest question of where you're wrong, and 'the discount widened instead' is a real, common, unglamorous outcome. A discount is a thesis with a number attached, and it needs a stop like everything else." },
        { kind: "keyIdea", title: "Two risks stacked on one position",
          text: "You carry the holdings' risk and the discount's risk simultaneously, and they correlate at the worst moment. In a panic, the portfolio falls and the discount widens at the same time, so the share price drops considerably more than the assets did. The same stacking runs in reverse during a boom, which is exactly why closed-end funds look brilliant late in a good year and why people buy them at premiums. Paying a premium means paying more than a dollar for a dollar of assets, and hoping the next person pays more still." },
        { kind: "prose", text: "Two more things to check before the discount seduces you. Many closed-end funds borrow — leverage amplifies the portfolio in both directions and adds interest-rate sensitivity that has nothing to do with what the fund holds. And many advertise a headline 'distribution rate' that isn't earned income: part of it can be return of capital, which means the fund is handing you back your own money and shrinking its NAV to do it. A high distribution funded that way is a slow liquidation with good marketing." },
        { kind: "quiz",
          question: "A closed-end fund's shares trade at $18 while its published NAV is $21. What does that tell you?",
          choices: [
            "The fund is mispriced and $3 of profit is available",
            "It trades at roughly a 14% discount — the market pays less than the holdings are worth, and the reason matters",
            "The NAV is wrong",
            "It's the same as an ETF trading slightly off its value",
          ],
          answer: 1,
          explain: "The gap is a fact: about a 14% discount. What it means is not. Fees, leverage, illiquid holdings, an unwanted manager, or simple indifference can all justify it, and nothing forces it to close. A measured gap is the start of the analysis, not the conclusion." },
        { kind: "quiz",
          question: "You buy at a 15% discount. Over the next year the fund's holdings gain 10%, but the discount widens to 25%. Roughly what happened to the share price you own?",
          choices: ["Up about 10%", "Up about 25%", "Down about 3%", "Unchanged"],
          answer: 2,
          explain: "Start with NAV 100 and a price of 85. NAV grows to 110; at a 25% discount the price is 110 × 0.75 = 82.5 — down about 3%. You were right about the portfolio and lost money anyway, because you also owned the discount. Two risks, one position." },
        { kind: "desk", instruction: "On Markets, open the Income pill and find a closed-end fund. Look up its NAV on the fund's own page, then put the two numbers in the formula above. Whatever the gap turns out to be, write down one sentence explaining why you think it exists. If you can't, you don't have a thesis — you have a number." },
        { kind: "flashcards", title: "Closed-end funds",
          cards: [
            { front: "Closed-end fund (CEF)", back: "A listed fund with a fixed share count — the price floats free of what it holds." },
            { front: "NAV", back: "Net asset value: what the holdings are worth per share, published daily." },
            { front: "Discount", back: "Price below NAV. Common, often rational, and under no obligation to close." },
            { front: "Premium", back: "Price above NAV — paying more than a dollar for a dollar of assets." },
            { front: "Return of capital", back: "A distribution paid out of your own money, shrinking NAV. Not income." },
            { front: "The stacked risk", back: "You own the holdings' risk AND the discount's risk — and they worsen together." },
          ] },
      ],
    },

    // ---------------------------------------------------------------
    {
      id: "w5-fx-pairs",
      title: "FX: currencies only trade in pairs",
      hook: "There is no such thing as being long the euro. You are long the euro and short something else, always.",
      minutes: 16,
      xp: 105,
      sections: [
        { kind: "analogy", title: "Every price is a price in something",
          text: "Asking what a euro is worth is like asking how tall a building is without saying in what — feet, floors, other buildings. A currency has no price of its own; it only has a price in another currency. EUR/USD at 1.08 says one euro costs 1.08 dollars, and that single number is a statement about two economies at once." },
        { kind: "prose", text: "So every FX quote names two currencies: the base (the first one, the thing being priced) and the quote (the second one, the thing it's priced in). Buy EUR/USD and you have bought euros by selling dollars — one order, two positions. Sell it and you've done the reverse. On the desk these carry an explicit FX: prefix, so FX:EURUSD displays as EUR/USD; the market runs about 24 hours a day, five days a week, opening Sunday evening and closing Friday evening, New York time. A one-unit move in the fourth decimal place is called a pip, which is the granularity most of this market speaks in." },
        { kind: "keyIdea", title: "Every FX trade contains two opinions",
          text: "A euro rally against the dollar can happen because Europe got better or because America got worse. Those are different theses with different evidence, and if you only hold one of them you have half a trade — the other half can quietly cancel you out. This is also why a view on one currency is best expressed against a currency you have the opposite view on, and why traders watch crosses (pairs with no dollar in them, like EUR/GBP) to isolate what the dollar is doing to everything." },
        { kind: "prose", text: "What actually moves pairs, roughly in order. Interest-rate differentials: money flows toward where it's paid more, and it moves on the expectation of a rate change long before the change happens — which is why currencies often move on a central banker's adjective. Growth and inflation surprises, for the same reason, since they shift what rates will do. Trade and capital flows, the slow tide underneath. Direct central-bank intervention, rare but violent. And risk sentiment: in a genuine panic, money runs toward the dollar, the yen and the franc regardless of what their economies are doing." },
        { kind: "keyIdea", title: "Leverage is what actually ruins people here",
          text: "A major pair often moves less than 1% in a day. That's the problem. To make a 0.5% move feel like money you have to borrow enormously, which is precisely why retail FX brokers advertise 50:1, 100:1, sometimes more. At 50:1, a $10,000 account controls $500,000, and a 2% move against you — an ordinary Tuesday — is the entire account. The market didn't become more dangerous; you did. Tars caps FX at 2:1, the same as equities, because a platform that hands a beginner 50:1 is not teaching trading, it is running a countdown." },
        { kind: "calc", tool: "position-size" },
        { kind: "prose", text: "The sizing math is exactly the one from Stage 4 and it does not change for currencies: your stop distance and your fixed 1% risk decide the size. The leverage available never enters the calculation. If the size that comes out of that formula would need more borrowing than you have, the answer is a smaller position, not a bigger loan. Nobody has ever been ruined by an unlevered currency position." },
        { kind: "prose", text: "Two specific ways this market hurts people. The carry trade — borrowing a low-yielding currency to hold a high-yielding one and pocketing the interest difference — pays a small amount every day for months and then hands it all back in a week when the trade unwinds, because everyone is in the same position and everyone exits through the same door. And gap risk: in January 2015 the Swiss central bank abandoned its cap on the franc, and EUR/CHF fell about 30% within minutes. Stops did not save people, because a stop is an instruction to trade at the market and for a while there was no market. Some accounts finished the morning owing money." },
        { kind: "quiz",
          question: "You buy EUR/USD. Which statement describes your actual position?",
          choices: [
            "Long the euro, with no other exposure",
            "Long the euro and short the dollar — one trade, two currencies",
            "Long both the euro and the dollar",
            "Short the euro against gold",
          ],
          answer: 1,
          explain: "Buying a pair means buying the base with the quote currency. You hold euros and owe dollars, so you profit if the euro rises against the dollar — and a dollar strong against everything can beat you even while the euro rises against everything else." },
        { kind: "quiz",
          question: "A $10,000 account at 50:1 leverage controls a $500,000 position. The pair moves 2% against you. What has happened?",
          choices: [
            "A 2% loss — $200",
            "A $10,000 loss — the entire account",
            "Nothing, since leverage doesn't affect losses",
            "A $1,000 loss",
          ],
          answer: 1,
          explain: "2% of $500,000 is $10,000, and the account was $10,000. The pair did something entirely ordinary; the leverage converted ordinary into fatal. This arithmetic is the whole reason the desk caps at 2:1 — at that level the same 2% move costs $400 and you're still trading tomorrow." },
        { kind: "desk", instruction: "Open FX:EURUSD on the desk. Read the quote as the sentence it actually is — 'one euro costs this many dollars' — and then say out loud which currency you'd be selling to buy the other. If you can't name both sides of the trade, you don't understand the position yet.", symbol: "FX:EURUSD" },
        { kind: "flashcards", title: "Currencies",
          cards: [
            { front: "Currency pair", back: "Two currencies quoted as a ratio — buying one always means selling the other." },
            { front: "Base / quote", back: "The first currency is being priced; the second is what it's priced in." },
            { front: "Pip", back: "The smallest conventional increment in a pair — usually the fourth decimal place." },
            { front: "Cross", back: "A pair with no dollar in it, used to isolate a view from the dollar's own move." },
            { front: "Rate differential", back: "The gap between two countries' interest rates — the biggest single driver of a pair." },
            { front: "Carry trade", back: "Holding a higher-yielding currency against a lower one for the interest — and the crowded exit." },
            { front: "Gap risk", back: "A price that jumps with no trading in between. Stops fill wherever the market reopens, not where you set them." },
          ] },
      ],
    },
  ],
};
